### ISSUE TITLE
Installing at Homey Pro Early 2023

### ISSUE THREAD

**Issue by MilanScherpen** [hteibler/eaton_docker#1]
Hello again,

I get the following error when trying to install this application. Could you help me please?

C:\Users\milan\OneDrive\Bureaublad\Eaton Homey>homey app install
× Error: Could not find a valid Homey App at 'C:\Users\milan\OneDrive\Bureaublad\Eaton Homey':
C:\Users\milan\OneDrive\Bureaublad\Eaton Homey\app.json: ENOENT: no such file or directory, open 'C:\Users\milan\OneDrive\Bureaublad\Eaton Homey\app.json'
    at App.getManifest (C:\Users\milan\AppData\Roaming\npm\node_modules\homey\lib\App.js:2850:13)
    at App.preprocess (C:\Users\milan\AppData\Roaming\npm\node_modules\homey\lib\App.js:801:11)
    at App.install (C:\Users\milan\AppData\Roaming\npm\node_modules\homey\lib\App.js:764:18)
    at exports.handler (C:\Users\milan\AppData\Roaming\npm\node_modules\homey\bin\cmds\app\install.js:25:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by hteibler** [comment]
this is not indented as a plugin for any system
instead as a middleware running on docker
